project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sobre_mim.qmd

format:
  html:
    theme: 
      - minty
      - minty.scss
    fontsize: 1rem
    fontcolor: "#000000"
    css: styles.css
    toc: true



